version: "3.9"
services:
  backend-service:
    build: 
      context: backend-service/
    environment:
      DOCKER_COMPOSE_STACK: "true"
    ports:
      - "8085:8085"
    networks:
      - host
  frontend-service:
    build: 
      context: frontend-service/
    environment:
      DOCKER_COMPOSE_STACK: "true"
    ports:
      - "3000:3000"
    links:
     - backend-service
    networks:
      - host
  redis:
    image: redis
    ports: 
      - "6379:6379"


networks:
  host: 